---
# This requires at least pandoc v2.15

#https://pandoc.org/MANUAL.html#metadata-variables

# Meta variables
title: Book title
author: author name
subtitle: subtitle goes here

# abstract: |
#   Abstract text goes here

keywords:
  - keyword1
  - keyword2
  - keyword3

# Language variables such as en-US, nl-BE, ...
lang: nl-BE

# Latex variables
# https://pandoc.org/MANUAL.html#variables-for-latex
documentclass: book
numbersections: false #number all heading1's
graphics: true

# Generate a table of contents
toc: true
toc-depth: 3
toc-title: Inhoudsopgave

lof: true # List of figures
lof-title: Lijst met afbeeldingen

lot: false # List of tables
lot-title: Lijst met tabellen

# Include a thanks footnote for the title
thanks: false

# Specify file without extension
appendix: build/latex/backmatter

# https://www.burble.co.za/files/Preparing_your_pages.pdf
# https://ftp.snt.utwente.nl/pub/software/tex/macros/latex/contrib/geometry/geometry.pdf
geometry:
  - paperwidth=170mm
  - paperheight=240mm
  - tmargin=25mm
  - bmargin=25mm
  - lmargin=19mm
  - rmargin=19mm

# Set line spacing
#linestretch: 1.25

preventligatures: false

# if true, pandoc will use document class settings for indentation (the default 
# LaTeX template otherwise removes indentation and adds space between paragraphs)
indent: false

# Color hyperlinks
colorlinks: false


# 10,11,12 supported
fontsize: 10pt
mainfont: SourceSerif4-Regular.ttf
mainfontoptions:
  - Path=resources/fonts/AdobeSourceSerif/
  - Scale=0.9
  - BoldFont=SourceSerif4-Bold.ttf
  - ItalicFont=SourceSerif4-It.ttf
  - BoldItalicFont=SourceSerif4-BoldIt.ttf
monofont: UbuntuMono-Regular.ttf
monofontoptions:
  - Path=resources/fonts/UbuntuMono/
  - Scale=0.8
sansfont: Ubuntu-Light.ttf
sansfontoptions:
  - Path=resources/fonts/Ubuntu/
  - Scale=1.0
  - BoldFont=Ubuntu-Bold.ttf
  - ItalicFont=Ubuntu-Italic.ttf
  - BoldItalicFont=Ubuntu-BoldItalic.ttf

# Filter preferences:
# - pandoc-crossref
linkReferences: true


# Script variables
default-image-width: 60         # default image width % used when a width is not specified
max-section-number-depth: 1     # until which level sections are numbered. Only works when
                                # numbersections is true
split-chapters:                 # chapters which should always start on a new page
  - Oefeningen